global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'solindexer-indexer'
    static_configs:
      - targets: ['indexer:9090']
    metrics_path: /metrics

  - job_name: 'solindexer-api'
    static_configs:
      - targets: ['api:4000']
    metrics_path: /metrics
